<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jm</string>
	</array>
	<key>name</key>
	<string>Jam</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#instruction</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>break</key>
		<dict>
			<key>match</key>
			<string>(break)</string>
			<key>name</key>
			<string>keyword.control.flow.jam</string>
		</dict>
		<key>builtins</key>
		<dict>
			<key>name</key>
			<string>support.jam</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>puts</string>
					<key>name</key>
					<string>support.function.jam</string>
				</dict>
				<dict>
					<key>match</key>
					<string>true|false|null</string>
					<key>name</key>
					<string>constant.language.jam</string>
				</dict>
				<dict>
					<key>match</key>
					<string>String|Int|Float|Bool</string>
					<key>name</key>
					<string>support.class.jam</string>
				</dict>
			</array>
		</dict>
		<key>class</key>
		<dict>
			<key>begin</key>
			<string>(class)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jam</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jam</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.jam</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constructor</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.jam</string>
		</dict>
		<key>constructor</key>
		<dict>
			<key>begin</key>
			<string>(new)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jam</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jam</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.constructor.jam</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#instruction</string>
				</dict>
			</array>
		</dict>
		<key>format-string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.jam</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.jam</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.jam</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-interp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-escape</string>
				</dict>
			</array>
		</dict>
		<key>identifier</key>
		<dict>
			<key>match</key>
			<string>[_a-zA-Z][_a-zA-Z0-9]*</string>
			<key>name</key>
			<string>entity.name.jam</string>
		</dict>
		<key>if</key>
		<dict>
			<key>begin</key>
			<string>(if)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.jam</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.jam</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.flow.jam</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(elif)</string>
					<key>name</key>
					<string>meta</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.flow.jam</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(else)</string>
					<key>name</key>
					<string>meta</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#instruction</string>
				</dict>
			</array>
		</dict>
		<key>import</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.jam</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(import)</string>
		</dict>
		<key>instruction</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#if</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#loops</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#return</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#break</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#import</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
			</array>
		</dict>
		<key>loops</key>
		<dict>
			<key>begin</key>
			<string>(while|loop)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.jam</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.jam</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#instruction</string>
				</dict>
			</array>
		</dict>
		<key>method</key>
		<dict>
			<key>begin</key>
			<string>(def)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jam</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jam</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.jam</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#instruction</string>
				</dict>
			</array>
		</dict>
		<key>modifiers</key>
		<dict>
			<key>match</key>
			<string>const</string>
			<key>name</key>
			<string>keyword.other.jam</string>
		</dict>
		<key>module</key>
		<dict>
			<key>begin</key>
			<string>(module)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jam</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(end)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.jam</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.module.jam</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#instruction</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>match</key>
			<string>\b([0-9]([0-9_]*[0-9])?)|(([0-9]([0-9_]*[0-9])?)?\.([0-9]([0-9_]*[0-9])?))|(([0-9]([0-9_]*[0-9])?)\.([0-9]([0-9_]*[0-9])?)?)\b</string>
			<key>name</key>
			<string>constant.numeric.jam</string>
		</dict>
		<key>object</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtins</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#format-string</string>
				</dict>
			</array>
		</dict>
		<key>return</key>
		<dict>
			<key>match</key>
			<string>(return)</string>
			<key>name</key>
			<string>keyword.control.flow.jam</string>
		</dict>
		<key>string-escape</key>
		<dict>
			<key>match</key>
			<string>(\\\\\")|(\\\\#\{)</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<key>string-interp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(#\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#object</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.jam</string>
	<key>uuid</key>
	<string>7424b099-61b0-471e-a716-4eb6aef06440</string>
</dict>
</plist>
